export default {
  MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
  MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID: 'MARK_ALL_NOTIFICATIONS_AS_READ_BY_ID',
  START_MARK_AS_READ: 'START_MARK_AS_READ',
  FINISH_MARK_AS_READ: 'FINISH_MARK_AS_READ',
  GET_NOTIFICATUION_DATA: 'GET_NOTIFICATUION_DATA',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  CHANGE_TX: 'CHANGE_TX'
}